#spring:
#  datasource:
#  url: jdbc:h2:tcp://localhost/~/reserve
#  username: sa
#  password:
#  driver-class-name: org.h2.Driver
#jpa:
#  hibernate:
#    ddl-auto: create
#  properties:
#    hibernate:
#      show_sql: true
#      format_sql: true
#    logging.level:
#      org.hibernate.type: trace #??? ?? 2.x, hibernate5
#      org.hibernate.SQL: debug
#      org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
server:
  address: 0.0.0.0
  port: 9999
  servlet:
    session:
      tracking-modes: cookie
spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://hamso-rds-instance.cd3bbnyyiapd.ap-northeast-2.rds.amazonaws.com:3306/hamsoDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: Hamso9800
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.type: trace
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
jwt:
  token:
    secret: "${JWT_SECRET}"

naver-cloud-sms:
  accessKey: "${ACCESS_KEY}"
  secretKey: "${SECRET_KEY}"
  serviceId: "${SERVICE_ID}"
  senderPhone: "${SENDER_PHONE}"


cloud:
  aws:
    s3:
      bucket: nongsa-bucket
    credentials:
      access-key: "${ACCESS_KEY}"
      secret-key: "${SECRET_KEY}"
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
